module.exports = {
	TEACHER_SIGNUP_PATH: '/api/v1/auth/teacher/signup',
	STUDENT_SIGNUP_PATH:'/api/v1/auth/student/signup',
	UPDATE_STUDENT_PATH:'/api/v1/auth/student/update',
	UPDATE_TEACHER_PATH:'/api/v1/auth/teacher/update',
	DELETE_STUDENT_PATH:'/api/v1/auth/student/delete',
	DELETE_TEACHER_PATH:'/api/v1/auth/teacher/delete',
	LOGIN_PATH: '/api/v1/auth/login',
	VIDEO_UPLOAD_PATH: '/api/v1/videos/upload',
	IMAGE_UPLOAD_PATH: '/api/v1/images/upload',
	CREATE_COURSE_PATH: '/api/v1/courses/create',
	DELETE_COURSE_PATH: '/api/v1/courses/delete',
	UPDATE_COURSE_PATH: '/api/v1/courses/update',
	SEARCH_COURSES_BY_NAME_FOR_TEACHER_PATH: '/api/v1/courses/search/teacher',
	SEARCH_COURSES_BY_NAME_PATH: '/api/v1/courses/search',
	GET_COURSES_STATUS_PATH: '/api/v1/courses/search/status',
	SEARCH_COURSES_BY_TEACHER_NAME_PATH: '/api/v1/courses/search/teacher-name',
	CREATE_CAROUSEL_ENTRY_PATH: '/api/v1/landing-page/carousel-slider/create',
	DELETE_CAROUSEL_ENTRY_PATH: '/api/v1/landing-page/carousel-slider/delete',
	UPDATE_CAROUSEL_ENTRY_PATH: '/api/v1/landing-page/carousel-slider/update',
	GET_OUR_TEACHERS_PATH: '/api/v1/landing-page/our-teachers',
	GET_OUT_COURSES_PATH: '/api/v1/landing-page/our-courses',
	GET_LANDING_PAGE_VIDEO_PATH: '/api/v1/landing-page/video',
	CREATE_LANDING_PAGE_VIDEO_PATH: '/api/v1/landing-page/create-video',
	UPDATE_LANDING_PAGE_VIDEO_PATH: '/api/v1/landing-page/update-video',
	DELETE_LANDING_PAGE_VIDEO_PATH: '/api/v1/landing-page/delete-video',
	GET_COURSES_ACCORDING_TO_YEAR_PATH : '/api/v1/courses/search/years-filter'
}